version: 2.1

jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          key: v5-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache  
      - run:
          when: always
          name: Run Tests with Coverage
          command: yarn run test
workflows:
  build-test:
    jobs:
      - test