version: 2.1

jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          key: v5-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache  
      - run:
          when: always
          name: Run Tests with Coverage
          command: yarn run test
      - run:
          name: Slack Custom Reporting
          when: always
          command: make slack-alert 
      - run:
          name: Full cypress run with reporting via script
          when: always
          command: make run-script 
      - run:
          name: Full cypress run with cypress-slack-reporter-full
          when: always
          command: ./node_modules/.bin/cypress-slack-reporter-full 
workflows:
  build-test:
    jobs:
      - test