version: '2.2'
services:
    cypresstestdocker:
        image: cypresstestdocker
        environment:
            - URI_ROOT=klook.com
            - SLACK_WEBHOOK = "https://hooks.slack.com/services/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"
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
volumes:
  node_modules: